export const seoConfig = {
  siteName: 'Nikki Technologies - CCTV, Digital Media & Software Solutions',
  siteUrl: 'https://nikkitechnologies.com',
  defaultTitle: 'Nikki Technologies | CCTV Installation, Digital Media & Software Solutions | Hyderabad, Telangana & AP',
  defaultDescription:
    'Nikki Technologies - your one-stop technology partner. Professional CCTV camera installation, digital marketing & media services, and software products (MyStore OS, Punchly, Jovio AI). Serving Hyderabad, Telangana and Andhra Pradesh. Free consultation.',
  keywords: [
    'Nikki Technologies', 'nikkitechnologies.com', 'Nikki Tech Hyderabad',
    'CCTV installation Hyderabad', 'CCTV camera installation Hyderabad', 'security camera installation Hyderabad',
    'CCTV installation Telangana', 'CCTV installation Andhra Pradesh', 'best CCTV company Hyderabad',
    'CCTV AMC Hyderabad', 'CCTV repair Hyderabad', 'IP camera installation Hyderabad', 'DVR NVR setup Hyderabad',
    'home CCTV installation Hyderabad', 'office CCTV installation Hyderabad', 'CCTV dealers Hyderabad',
    'biometric attendance system Hyderabad', 'access control installation Hyderabad',
    'digital marketing agency Hyderabad', 'social media marketing Hyderabad', 'digital media services Hyderabad',
    'branding agency Hyderabad', 'video production Hyderabad', 'Instagram marketing Hyderabad',
    'Google ads agency Hyderabad', 'Meta ads agency Hyderabad', 'performance marketing Hyderabad',
    'content creation Hyderabad', 'reels production Hyderabad', 'logo design Hyderabad',
    'software company Hyderabad', 'custom software development Hyderabad', 'SaaS products India',
    'retail billing software India', 'MyStore OS', 'attendance payroll software India', 'Punchly',
    'AI voice bot Telugu', 'Jovio AI', 'web development Hyderabad', 'mobile app development Hyderabad',
    'business automation software Hyderabad', 'GST billing software India',
  ],
  contact: {
    phone: '+91 00000 00000',
    whatsapp: '+91 00000 00000',
    email: 'info@nikkitechnologies.com',
    address: 'Hyderabad, Telangana, India',
  },
  social: { facebook: '', instagram: '', youtube: '', linkedin: '' },
  geo: { region: 'IN-TG', placename: 'Hyderabad', latitude: 17.385, longitude: 78.4867 },
  organization: {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Nikki Technologies',
    url: 'https://nikkitechnologies.com',
    logo: 'https://nikkitechnologies.com/logo.png',
    description: 'CCTV installation, digital media services and software solutions company based in Hyderabad, serving Telangana and Andhra Pradesh.',
    address: { '@type': 'PostalAddress', addressLocality: 'Hyderabad', addressRegion: 'Telangana', addressCountry: 'IN' },
    areaServed: ['Hyderabad', 'Telangana', 'Andhra Pradesh'],
    department: [
      { '@type': 'Organization', name: 'CCTV Installation', description: 'Security camera installation, AMC and access control' },
      { '@type': 'Organization', name: 'Digital Media', description: 'Digital marketing, branding and video production' },
      { '@type': 'Organization', name: 'Software Solutions', description: 'SaaS products - MyStore OS, Punchly, Jovio AI - and custom software' },
    ],
  },
};
