/*
  # Reporting time on onboarding + segment-specific offer/welcome letters + job description doc type
*/

ALTER TABLE app_users ADD COLUMN IF NOT EXISTS reporting_time text DEFAULT '';

-- Allow 'job_description' as a document type
ALTER TABLE document_templates DROP CONSTRAINT IF EXISTS document_templates_doc_type_check;
ALTER TABLE document_templates ADD CONSTRAINT document_templates_doc_type_check
  CHECK (doc_type IN ('offer_letter','welcome_letter','roles_responsibilities','job_description','policy','other'));

ALTER TABLE employee_documents DROP CONSTRAINT IF EXISTS employee_documents_doc_type_check;
ALTER TABLE employee_documents ADD CONSTRAINT employee_documents_doc_type_check
  CHECK (doc_type IN ('offer_letter','welcome_letter','roles_responsibilities','job_description','policy','other'));

-- Replace the generic company-wide offer/welcome letters with segment-specific versions
-- (mentions division, reporting time, and shift explicitly — not just placeholders).
DELETE FROM document_templates WHERE doc_type IN ('offer_letter','welcome_letter') AND segment_slug IS NULL;

INSERT INTO document_templates (segment_slug, doc_type, title, body, requires_signature) VALUES
  ('cctv', 'offer_letter', 'Offer Letter — CCTV Installation', E'Dear {{name}},\n\nWe are pleased to offer you the position of {{designation}} in the CCTV Installation division of Nikki Technologies, reporting from {{joining_date}}.\n\nReporting Time / Shift: {{reporting_time}}\nEmployment Type: {{employment_type}}\nCompensation (Annual CTC): ₹{{ctc}}\n\nYour role will involve on-site installation, AMC visits and client-facing technical work as part of our CCTV team. This offer is subject to our standard company policies and code of conduct. Please confirm your acceptance by signing this letter in your staff portal.\n\nWe look forward to having you on the team.\n\nRegards,\nNikki Technologies HR', true),
  ('digital_media', 'offer_letter', 'Offer Letter — Digital Media', E'Dear {{name}},\n\nWe are pleased to offer you the position of {{designation}} in the Digital Media division of Nikki Technologies, reporting from {{joining_date}}.\n\nReporting Time / Shift: {{reporting_time}}\nEmployment Type: {{employment_type}}\nCompensation (Annual CTC): ₹{{ctc}}\n\nYou will be joining our content, campaigns and client-servicing team, working on social media, branding and performance marketing. This offer is subject to our standard company policies and code of conduct. Please confirm your acceptance by signing this letter in your staff portal.\n\nWe look forward to having you on the team.\n\nRegards,\nNikki Technologies HR', true),
  ('software', 'offer_letter', 'Offer Letter — Software Solutions', E'Dear {{name}},\n\nWe are pleased to offer you the position of {{designation}} in the Software Solutions division of Nikki Technologies, reporting from {{joining_date}}.\n\nReporting Time / Shift: {{reporting_time}}\nEmployment Type: {{employment_type}}\nCompensation (Annual CTC): ₹{{ctc}}\n\nYou will be working on our SaaS products and client software projects as part of the engineering team. This offer is subject to our standard company policies and code of conduct. Please confirm your acceptance by signing this letter in your staff portal.\n\nWe look forward to having you on the team.\n\nRegards,\nNikki Technologies HR', true),
  ('cctv', 'welcome_letter', 'Welcome Letter — CCTV Installation', E'Dear {{name}},\n\nWelcome to Nikki Technologies! We are delighted to have you join our CCTV Installation team as {{designation}}, effective {{joining_date}}.\n\nYour reporting time will be {{reporting_time}}. Your manager and HR are always available to help you settle in — please don''t hesitate to reach out with any questions about tools, sites, or schedules.\n\nWarm regards,\nNikki Technologies', true),
  ('digital_media', 'welcome_letter', 'Welcome Letter — Digital Media', E'Dear {{name}},\n\nWelcome to Nikki Technologies! We are delighted to have you join our Digital Media team as {{designation}}, effective {{joining_date}}.\n\nYour reporting time will be {{reporting_time}}. Your manager and HR are always available to help you settle in — please don''t hesitate to reach out with any questions about tools, clients, or schedules.\n\nWarm regards,\nNikki Technologies', true),
  ('software', 'welcome_letter', 'Welcome Letter — Software Solutions', E'Dear {{name}},\n\nWelcome to Nikki Technologies! We are delighted to have you join our Software Solutions team as {{designation}}, effective {{joining_date}}.\n\nYour reporting time will be {{reporting_time}}. Your manager and HR are always available to help you settle in — please don''t hesitate to reach out with any questions about tools, repos, or schedules.\n\nWarm regards,\nNikki Technologies', true);

-- Sample job description templates (Super Admin can edit/add more per specific designation)
INSERT INTO document_templates (segment_slug, doc_type, title, body, requires_signature) VALUES
  ('cctv', 'job_description', 'Job Description — CCTV Field Technician', E'Position: {{designation}}\nDivision: CCTV Installation\nReports to: Segment Manager\nReporting Time: {{reporting_time}}\n\nPurpose of Role:\nInstall, configure and maintain CCTV and security systems at client sites to a professional standard.\n\nKey Duties:\n- Install cameras, DVR/NVR, cabling and access control hardware\n- Perform AMC visits and repair tickets within SLA\n- Test and configure remote viewing for clients\n- Maintain accurate site and material records\n- Follow safety procedures at all times\n\nSkills Required: Basic electrical/networking knowledge, two-wheeler license preferred, customer-facing communication.', false),
  ('digital_media', 'job_description', 'Job Description — Digital Media Executive', E'Position: {{designation}}\nDivision: Digital Media\nReports to: Segment Manager\nReporting Time: {{reporting_time}}\n\nPurpose of Role:\nPlan and execute social media, content and ad campaigns for client accounts.\n\nKey Duties:\n- Build and maintain content calendars\n- Design creatives and short-form video content\n- Manage and optimize paid campaigns (Meta/Google)\n- Report weekly performance metrics\n- Coordinate approvals with clients\n\nSkills Required: Design/editing tools familiarity, strong communication, basic analytics.', false),
  ('software', 'job_description', 'Job Description — Software Developer', E'Position: {{designation}}\nDivision: Software Solutions\nReports to: Segment Manager\nReporting Time: {{reporting_time}}\n\nPurpose of Role:\nBuild and maintain features for Nikki Technologies products and client projects.\n\nKey Duties:\n- Write, test and review code per team standards\n- Resolve support tickets within SLA\n- Participate in architecture and planning discussions\n- Document technical decisions\n- Protect client and company data at all times\n\nSkills Required: Proficiency in the team''s primary stack, Git workflow, clear written communication.', false);
